### ISSUE TITLE
actions docs clarification

### ISSUE THREAD

**Issue by chrisjsimpson** [houseabsolute/actions-rust-release#1]
thank you fro making this useful tool!

The [README](https://github.com/houseabsolute/actions-rust-release/blob/v0/README.md) states:
> If this action is called for a tag that matches the specified prefix (defaults to v), then it will also create/update a GitHub Release for this tag, attaching the archive and checksum files as release artifacts

Sorry I'm not understanding from that readme how to configure `actions-rust-release` in such a way that when builds complete, the uploaded artifacts are associated with the release. I'm modeling based on your ubi repo

Please kindly let me know if you see[ I'm missing ](https://github.com/chrisjsimpson/ansible-vault-vars-decryptor/commit/6ce3f0439cc024837ab5a2e0ae1f741a735d4c19)something probaly very obvious, thanks!

- Are you *manually* `git tag x` 'ing and pushing your git tags to trigger the release?
- I'm familar with using `[auto](https://github.com/intuit/auto)` to do automated changelog + git tagging.

**Comment by autarch** [comment]
I think anything that creates a tag in the GitHub repo will trigger this. I'm using [`cargo-release`](https://github.com/crate-ci/cargo-release) locally, which uploads the crate to crates.io, creates a git tag, and pushes that tag back to the repo. But you could do these things by hand too.

**Comment by autarch** [comment]
Ok to close this ticket?
